name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-build-test:
      name: Build & Smoke Test Docker Image
      runs-on: ubuntu-latest
      
      env:
        IMAGE_TAG: bruker2mzml:ci-test

      steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG
      - name: Test the Docker container runs
        run: docker run --rm $IMAGE_TAG --help || true
